### ISSUE TITLE
TypeError: data type 'Float64' not understood

### ISSUE THREAD

**Issue by rahulbhadani** [QSong-github/scGCN#3]
I tried to reproduce the example as explained in the README of the repo.

There was one minor issue where `train.py` expects  file name _input/Label1.csv_ however Rscript `data_preprocess.R` generates  _input/label1.csv_ . So I had to manually rename to match Upper case letter L.

Then I called `python train.py` on the example data and I got the following error:

```
WARNING:tensorflow:From train.py:20: The name tf.set_random_seed is deprecated. Please use tf.compat.v1.set_random_seed instead.

Traceback (most recent call last):
  File "train.py", line 42, in <module>
    FLAGS.dataset,rgraph=FLAGS.graph)
  File "/home/refulgent/VersionControl/scGCN/scGCN/utils.py", line 70, in load_data
    datas_tr = scipy.sparse.csr_matrix(datas_train.astype('Float64'))
TypeError: data type 'Float64' not understood

```

I suspect it might have something to do with what version of pandas and scipy is being used for the reproduction of the results from `scGCN`.

Following are versions of all packages in my python environment which I got by typing `conda list`

```
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
absl-py                   0.13.0                   pypi_0    pypi
argcomplete               1.12.3                   pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
ca-certificates           2021.7.5             h06a4308_1  
cached-property           1.5.2                    pypi_0    pypi
certifi                   2021.5.30        py37h06a4308_0  
debugpy                   1.4.1                    pypi_0    pypi
decorator                 5.0.9                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.39.0                   pypi_0    pypi
h5py                      3.3.0                    pypi_0    pypi
importlib-metadata        4.6.4                    pypi_0    pypi
ipykernel                 6.2.0                    pypi_0    pypi
ipython                   7.26.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
jupyter-client            7.0.1                    pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libstdcxx-ng              9.3.0               hd4cf53a_17  
markdown                  3.3.4                    pypi_0    pypi
matplotlib-inline         0.1.2                    pypi_0    pypi
mock                      4.0.3                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1                    pypi_0    pypi
networkx                  2.2                      pypi_0    pypi
numpy                     1.21.2                   pypi_0    pypi
openssl                   1.1.1k               h27cfd23_0  
opt-einsum                3.3.0                    pypi_0    pypi
pandas                    1.3.3                    pypi_0    pypi
parso                     0.8.2                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       21.0.1           py37h06a4308_0  
prompt-toolkit            3.0.20                   pypi_0    pypi
protobuf                  3.17.3                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pygments                  2.10.0                   pypi_0    pypi
python                    3.7.11               h12debd9_0  
python-dateutil           2.8.2                    pypi_0    pypi
pytz                      2021.1                   pypi_0    pypi
pyzmq                     22.2.1                   pypi_0    pypi
readline                  8.1                  h27cfd23_0  
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.1.0                    pypi_0    pypi
setuptools                41.0.0                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sklearn                   0.0                      pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0  
tensorboard               1.15.0                   pypi_0    pypi
tensorflow                1.15.0                   pypi_0    pypi
tensorflow-estimator      1.15.1                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             2.2.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
tornado                   6.1                      pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typing-extensions         3.10.0.0                 pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
werkzeug                  2.0.1                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_0  
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
zipp                      3.5.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  

```

Any help on this would be greatly appreciated.

**Comment by QSong-github** [comment]
Okay I see. This error should be due to the version. The easiest way is to change "Float64" as "float64".

**Comment by rahulbhadani** [comment]
Thank you for the reply. Your solution in this case was able to fix the error. However, I am not sure by I cannot run the same with GEO 108989 dataset. I will close this issue and log a different issue related to the 108989 dataset.
